### ISSUE TITLE
bug: Powershell doesn't work

### ISSUE THREAD

**Issue by marc2332** [KRTirtho/wives#11]
**Describe the bug**
Powershell doesn't work.

**To Reproduce**
1. Launch powershell

**Expected behavior**
To work

**Screenshots**

![image](https://user-images.githubusercontent.com/38158676/206858755-d4626301-8d2b-48aa-8f07-c7a58d81c987.png)
![image](https://user-images.githubusercontent.com/38158676/206858771-53127ac1-0616-4bd0-a76e-9de03f3e8d48.png)

**Desktop**
 - OS: Windows 11
 - Version: v0.1.0

**Comment by KRTirtho** [comment]
Powershell doesn't work? That's a bit odd. Don't worry, I'll look into it

**Comment by KRTirtho** [comment]
The latest bugfix 0.1.1 fixes this issue although powershell v7 is untested in windows

**Comment by marc2332** [comment]
it works now!

![image](https://user-images.githubusercontent.com/38158676/206921423-81428879-e2f7-419a-8a3a-750d93210dcd.png)

Closing this 👍

**Comment by KRTirtho** [comment]
You're using starship with powershell. Awesome
