### ISSUE TITLE
App doesn't Work on MacOs

### ISSUE THREAD

**Issue by FotieMConstant** [KRTirtho/wives#8]
**Describe the bug**
Doesn't work on MacOs

**To Reproduce**
install the software on mac and launch

**Expected behavior**
should be able to work on macOs

**Screenshots**
<img width="801" alt="image" src="https://user-images.githubusercontent.com/42372656/204084255-7437cb1b-73d5-4b31-b8ab-4b25197cc350.png">

**Desktop (please complete the following information):**
 - OS: MacOs
 - Version: 11.7.1

**Comment by KRTirtho** [comment]
@FotieMConstant Can you try now with latest nightly?
